
import { Paint, PaintType } from './types';

export const INITIAL_PAINTS: Paint[] = [
  // --- BASE ---
  { id: 'b1', name: 'Abaddon Black', type: PaintType.Base, hex: '#231f20', owned: false, wishlist: false },
  { id: 'b2', name: 'Corax White', type: PaintType.Base, hex: '#ffffff', owned: false, wishlist: false },
  { id: 'b3', name: 'Mechanicus Standard Grey', type: PaintType.Base, hex: '#3d4547', owned: false, wishlist: false },
  { id: 'b4', name: 'Retributor Armour', type: PaintType.Base, hex: '#c1974d', owned: false, wishlist: false },
  { id: 'b5', name: 'Leadbelcher', type: PaintType.Base, hex: '#888d8f', owned: false, wishlist: false },
  { id: 'b6', name: 'Averland Sunset', type: PaintType.Base, hex: '#fbb81c', owned: false, wishlist: false },
  { id: 'b7', name: 'Mephiston Red', type: PaintType.Base, hex: '#960c12', owned: false, wishlist: false },
  { id: 'b8', name: 'Khorne Red', type: PaintType.Base, hex: '#6a0001', owned: false, wishlist: false },
  { id: 'b9', name: 'Kantor Blue', type: PaintType.Base, hex: '#02134e', owned: false, wishlist: false },
  { id: 'b10', name: 'Macragge Blue', type: PaintType.Base, hex: '#0d407f', owned: false, wishlist: false },
  { id: 'b11', name: 'Caledor Sky', type: PaintType.Base, hex: '#366698', owned: false, wishlist: false },
  { id: 'b12', name: 'Stegadon Scale Green', type: PaintType.Base, hex: '#074358', owned: false, wishlist: false },
  { id: 'b13', name: 'Incubi Darkness', type: PaintType.Base, hex: '#0b474a', owned: false, wishlist: false },
  { id: 'b14', name: 'Caliban Green', type: PaintType.Base, hex: '#00402e', owned: false, wishlist: false },
  { id: 'b15', name: 'Waaagh! Flesh', type: PaintType.Base, hex: '#1e5732', owned: false, wishlist: false },
  { id: 'b16', name: 'Castellan Green', type: PaintType.Base, hex: '#30492b', owned: false, wishlist: false },
  { id: 'b17', name: 'Death Guard Green', type: PaintType.Base, hex: '#6d764d', owned: false, wishlist: false },
  { id: 'b18', name: 'Zandri Dust', type: PaintType.Base, hex: '#9e915c', owned: false, wishlist: false },
  { id: 'b19', name: 'Rakarth Flesh', type: PaintType.Base, hex: '#9c988d', owned: false, wishlist: false },
  { id: 'b20', name: 'Bugman\'s Glow', type: PaintType.Base, hex: '#804c43', owned: false, wishlist: false },
  { id: 'b21', name: 'Ratskin Flesh', type: PaintType.Base, hex: '#a86647', owned: false, wishlist: false },
  { id: 'b22', name: 'Jokaero Orange', type: PaintType.Base, hex: '#ea5326', owned: false, wishlist: false },
  { id: 'b23', name: 'Grey Seer', type: PaintType.Base, hex: '#aebec1', owned: false, wishlist: false },
  { id: 'b24', name: 'Wraithbone', type: PaintType.Base, hex: '#ded4b6', owned: false, wishlist: false },
  { id: 'b25', name: 'Thousand Sons Blue', type: PaintType.Base, hex: '#136b86', owned: false, wishlist: false },
  { id: 'b26', name: 'Lupercal Green', type: PaintType.Base, hex: '#002b2d', owned: false, wishlist: false },
  { id: 'b27', name: 'Phoenician Purple', type: PaintType.Base, hex: '#4d2d58', owned: false, wishlist: false },
  { id: 'b28', name: 'Naggaroth Night', type: PaintType.Base, hex: '#3d3354', owned: false, wishlist: false },
  { id: 'b29', name: 'Daemonette Hide', type: PaintType.Base, hex: '#665776', owned: false, wishlist: false },
  { id: 'b30', name: 'Screamer Pink', type: PaintType.Base, hex: '#7a1d47', owned: false, wishlist: false },
  { id: 'b31', name: 'Barak-Nar Burgundy', type: PaintType.Base, hex: '#441625', owned: false, wishlist: false },
  { id: 'b32', name: 'Gal Vorbak Red', type: PaintType.Base, hex: '#4b2225', owned: false, wishlist: false },
  { id: 'b33', name: 'Catachan Fleshtone', type: PaintType.Base, hex: '#4e3327', owned: false, wishlist: false },
  { id: 'b34', name: 'Rhinox Hide', type: PaintType.Base, hex: '#46352e', owned: false, wishlist: false },
  { id: 'b35', name: 'Dryad Bark', type: PaintType.Base, hex: '#332b27', owned: false, wishlist: false },
  { id: 'b36', name: 'Mournfang Brown', type: PaintType.Base, hex: '#623f26', owned: false, wishlist: false },
  { id: 'b37', name: 'XV-88', type: PaintType.Base, hex: '#714b27', owned: false, wishlist: false },
  { id: 'b38', name: 'Steel Legion Drab', type: PaintType.Base, hex: '#5d513e', owned: false, wishlist: false },
  { id: 'b39', name: 'Morghast Bone', type: PaintType.Base, hex: '#c3b284', owned: false, wishlist: false },
  { id: 'b40', name: 'The Fang', type: PaintType.Base, hex: '#405762', owned: false, wishlist: false },
  { id: 'b41', name: 'Ionrach Skin', type: PaintType.Base, hex: '#99a38b', owned: false, wishlist: false },
  { id: 'b42', name: 'Deepkin Flesh', type: PaintType.Base, hex: '#a8b79d', owned: false, wishlist: false },
  { id: 'b43', name: 'Celestra Grey', type: PaintType.Base, hex: '#8c999b', owned: false, wishlist: false },
  { id: 'b44', name: 'Night Lords Blue', type: PaintType.Base, hex: '#002b50', owned: false, wishlist: false },
  { id: 'b45', name: 'Corvus Black', type: PaintType.Base, hex: '#171717', owned: false, wishlist: false },
  { id: 'b46', name: 'Balthasar Gold', type: PaintType.Base, hex: '#a47550', owned: false, wishlist: false },
  { id: 'b47', name: 'Screaming Bell', type: PaintType.Base, hex: '#b66235', owned: false, wishlist: false },
  { id: 'b48', name: 'Warplock Bronze', type: PaintType.Base, hex: '#534440', owned: false, wishlist: false },
  { id: 'b49', name: 'Iron Hands Steel', type: PaintType.Base, hex: '#6b6b6b', owned: false, wishlist: false },
  { id: 'b50', name: 'Grey Knights Steel', type: PaintType.Base, hex: '#8ca1a8', owned: false, wishlist: false },
  { id: 'b51', name: 'Runelord Brass', type: PaintType.Base, hex: '#9f886a', owned: false, wishlist: false },

  // --- LAYER ---
  { id: 'l1', name: 'Eshin Grey', type: PaintType.Layer, hex: '#4a4f52', owned: false, wishlist: false },
  { id: 'l2', name: 'Dawnstone', type: PaintType.Layer, hex: '#6e7578', owned: false, wishlist: false },
  { id: 'l3', name: 'Administratum Grey', type: PaintType.Layer, hex: '#8f9898', owned: false, wishlist: false },
  { id: 'l4', name: 'White Scar', type: PaintType.Layer, hex: '#ffffff', owned: false, wishlist: false },
  { id: 'l5', name: 'Ulthuan Grey', type: PaintType.Layer, hex: '#c4d1d3', owned: false, wishlist: false },
  { id: 'l6', name: 'Pallid Wych Flesh', type: PaintType.Layer, hex: '#d3d0c6', owned: false, wishlist: false },
  { id: 'l7', name: 'Evil Sunz Scarlet', type: PaintType.Layer, hex: '#c01411', owned: false, wishlist: false },
  { id: 'l8', name: 'Wild Rider Red', type: PaintType.Layer, hex: '#e82e1b', owned: false, wishlist: false },
  { id: 'l9', name: 'Wazdakka Red', type: PaintType.Layer, hex: '#870813', owned: false, wishlist: false },
  { id: 'l10', name: 'Squig Orange', type: PaintType.Layer, hex: '#a74d41', owned: false, wishlist: false },
  { id: 'l11', name: 'Troll Slayer Orange', type: PaintType.Layer, hex: '#f06a23', owned: false, wishlist: false },
  { id: 'l12', name: 'Fire Dragon Bright', type: PaintType.Layer, hex: '#f48644', owned: false, wishlist: false },
  { id: 'l13', name: 'Flash Gitz Yellow', type: PaintType.Layer, hex: '#fff300', owned: false, wishlist: false },
  { id: 'l14', name: 'Yriel Yellow', type: PaintType.Layer, hex: '#ffdc00', owned: false, wishlist: false },
  { id: 'l15', name: 'Phalanx Yellow', type: PaintType.Layer, hex: '#ffe856', owned: false, wishlist: false },
  { id: 'l16', name: 'Moot Green', type: PaintType.Layer, hex: '#52b244', owned: false, wishlist: false },
  { id: 'l17', name: 'Warboss Green', type: PaintType.Layer, hex: '#347a43', owned: false, wishlist: false },
  { id: 'l18', name: 'Skarsnik Green', type: PaintType.Layer, hex: '#588f68', owned: false, wishlist: false },
  { id: 'l19', name: 'Straken Green', type: PaintType.Layer, hex: '#5f7d3b', owned: false, wishlist: false },
  { id: 'l20', name: 'Nurgling Green', type: PaintType.Layer, hex: '#809d6f', owned: false, wishlist: false },
  { id: 'l21', name: 'Elysian Green', type: PaintType.Layer, hex: '#738d48', owned: false, wishlist: false },
  { id: 'l22', name: 'Ogryn Camo', type: PaintType.Layer, hex: '#96a656', owned: false, wishlist: false },
  { id: 'l23', name: 'Loren Forest', type: PaintType.Layer, hex: '#4d6641', owned: false, wishlist: false },
  { id: 'l24', name: 'Alaitoc Blue', type: PaintType.Layer, hex: '#275286', owned: false, wishlist: false },
  { id: 'l25', name: 'Hoeth Blue', type: PaintType.Layer, hex: '#4b7fb3', owned: false, wishlist: false },
  { id: 'l26', name: 'Lothern Blue', type: PaintType.Layer, hex: '#2c9cc3', owned: false, wishlist: false },
  { id: 'l27', name: 'Altdorf Guard Blue', type: PaintType.Layer, hex: '#1f56a7', owned: false, wishlist: false },
  { id: 'l28', name: 'Calgar Blue', type: PaintType.Layer, hex: '#4066a5', owned: false, wishlist: false },
  { id: 'l29', name: 'Fenrisian Grey', type: PaintType.Layer, hex: '#7091b3', owned: false, wishlist: false },
  { id: 'l30', name: 'Russ Grey', type: PaintType.Layer, hex: '#506d84', owned: false, wishlist: false },
  { id: 'l31', name: 'Teclis Blue', type: PaintType.Layer, hex: '#317fc6', owned: false, wishlist: false },
  { id: 'l32', name: 'Temple Guard Blue', type: PaintType.Layer, hex: '#318c90', owned: false, wishlist: false },
  { id: 'l33', name: 'Sotek Green', type: PaintType.Layer, hex: '#0d6b75', owned: false, wishlist: false },
  { id: 'l34', name: 'Baharroth Blue', type: PaintType.Layer, hex: '#57becd', owned: false, wishlist: false },
  { id: 'l35', name: 'Blue Horror', type: PaintType.Layer, hex: '#9eb4c2', owned: false, wishlist: false },
  { id: 'l36', name: 'Warpfiend Grey', type: PaintType.Layer, hex: '#646169', owned: false, wishlist: false },
  { id: 'l37', name: 'Slaanesh Grey', type: PaintType.Layer, hex: '#8b8893', owned: false, wishlist: false },
  { id: 'l38', name: 'Gorthor Brown', type: PaintType.Layer, hex: '#5e4638', owned: false, wishlist: false },
  { id: 'l39', name: 'Baneblade Brown', type: PaintType.Layer, hex: '#8f7b68', owned: false, wishlist: false },
  { id: 'l40', name: 'Karak Stone', type: PaintType.Layer, hex: '#b29e72', owned: false, wishlist: false },
  { id: 'l41', name: 'Cadian Fleshtone', type: PaintType.Layer, hex: '#c4765d', owned: false, wishlist: false },
  { id: 'l42', name: 'Kislev Flesh', type: PaintType.Layer, hex: '#d1a57a', owned: false, wishlist: false },
  { id: 'l43', name: 'Flayed One Flesh', type: PaintType.Layer, hex: '#e2cfb2', owned: false, wishlist: false },
  { id: 'l44', name: 'Bestigor Flesh', type: PaintType.Layer, hex: '#d08b58', owned: false, wishlist: false },
  { id: 'l45', name: 'Ungor Flesh', type: PaintType.Layer, hex: '#d4a565', owned: false, wishlist: false },
  { id: 'l46', name: 'Ushabti Bone', type: PaintType.Layer, hex: '#bfbb8e', owned: false, wishlist: false },
  { id: 'l47', name: 'Screaming Skull', type: PaintType.Layer, hex: '#d5d0b2', owned: false, wishlist: false },
  { id: 'l48', name: 'Tau Light Ochre', type: PaintType.Layer, hex: '#bc6e1f', owned: false, wishlist: false },
  { id: 'l49', name: 'Balor Brown', type: PaintType.Layer, hex: '#87551d', owned: false, wishlist: false },
  { id: 'l50', name: 'Zamesi Desert', type: PaintType.Layer, hex: '#d69b26', owned: false, wishlist: false },
  { id: 'l51', name: 'Doombull Brown', type: PaintType.Layer, hex: '#570100', owned: false, wishlist: false },
  { id: 'l52', name: 'Tuskgor Fur', type: PaintType.Layer, hex: '#863230', owned: false, wishlist: false },
  { id: 'l53', name: 'Pink Horror', type: PaintType.Layer, hex: '#8f325d', owned: false, wishlist: false },
  { id: 'l54', name: 'Emperor\'s Children', type: PaintType.Layer, hex: '#b74073', owned: false, wishlist: false },
  { id: 'l55', name: 'Xereus Purple', type: PaintType.Layer, hex: '#471f5e', owned: false, wishlist: false },
  { id: 'l56', name: 'Genestealer Purple', type: PaintType.Layer, hex: '#7658a5', owned: false, wishlist: false },
  { id: 'l57', name: 'Kakophoni Purple', type: PaintType.Layer, hex: '#85528d', owned: false, wishlist: false },
  { id: 'l58', name: 'Dechala Lilac', type: PaintType.Layer, hex: '#b293c7', owned: false, wishlist: false },
  { id: 'l59', name: 'Sybarite Green', type: PaintType.Layer, hex: '#30a36d', owned: false, wishlist: false },
  { id: 'l60', name: 'Kabalite Green', type: PaintType.Layer, hex: '#038a68', owned: false, wishlist: false },
  { id: 'l61', name: 'Gauss Blaster Green', type: PaintType.Layer, hex: '#7fc1a5', owned: false, wishlist: false },
  { id: 'l62', name: 'Ironbreaker', type: PaintType.Layer, hex: '#9fa5a7', owned: false, wishlist: false },
  { id: 'l63', name: 'Runefang Steel', type: PaintType.Layer, hex: '#c2c6ca', owned: false, wishlist: false },
  { id: 'l64', name: 'Stormhost Silver', type: PaintType.Layer, hex: '#cfd6d8', owned: false, wishlist: false },
  { id: 'l65', name: 'Gehenna\'s Gold', type: PaintType.Layer, hex: '#c16f30', owned: false, wishlist: false },
  { id: 'l66', name: 'Auric Armour Gold', type: PaintType.Layer, hex: '#e6bd62', owned: false, wishlist: false },
  { id: 'l67', name: 'Liberator Gold', type: PaintType.Layer, hex: '#d2a148', owned: false, wishlist: false },
  { id: 'l68', name: 'Sycorax Bronze', type: PaintType.Layer, hex: '#c5a685', owned: false, wishlist: false },
  { id: 'l69', name: 'Brass Scorpion', type: PaintType.Layer, hex: '#b37132', owned: false, wishlist: false },
  { id: 'l70', name: 'Canoptek Alloy', type: PaintType.Layer, hex: '#a59087', owned: false, wishlist: false },
  { id: 'l71', name: 'Castellax Bronze', type: PaintType.Layer, hex: '#8c572e', owned: false, wishlist: false },
  { id: 'l72', name: 'Fulgurite Copper', type: PaintType.Layer, hex: '#c7874b', owned: false, wishlist: false },
  { id: 'l73', name: 'Skullcrusher Brass', type: PaintType.Layer, hex: '#d8a95a', owned: false, wishlist: false },

  // --- SHADE ---
  { id: 's1', name: 'Nuln Oil', type: PaintType.Shade, hex: '#1a1a1a', owned: false, wishlist: false },
  { id: 's2', name: 'Agrax Earthshade', type: PaintType.Shade, hex: '#3f2d1d', owned: false, wishlist: false },
  { id: 's3', name: 'Reikland Fleshshade', type: PaintType.Shade, hex: '#7d4b39', owned: false, wishlist: false },
  { id: 's4', name: 'Seraphim Sepia', type: PaintType.Shade, hex: '#77431c', owned: false, wishlist: false },
  { id: 's5', name: 'Cassandora Yellow', type: PaintType.Shade, hex: '#d19822', owned: false, wishlist: false },
  { id: 's6', name: 'Fuegan Orange', type: PaintType.Shade, hex: '#8c421f', owned: false, wishlist: false },
  { id: 's7', name: 'Carroburg Crimson', type: PaintType.Shade, hex: '#5b1027', owned: false, wishlist: false },
  { id: 's8', name: 'Druchii Violet', type: PaintType.Shade, hex: '#4b2346', owned: false, wishlist: false },
  { id: 's9', name: 'Drakenhof Nightshade', type: PaintType.Shade, hex: '#1a2742', owned: false, wishlist: false },
  { id: 's10', name: 'Coelia Greenshade', type: PaintType.Shade, hex: '#184642', owned: false, wishlist: false },
  { id: 's11', name: 'Biel-Tan Green', type: PaintType.Shade, hex: '#144626', owned: false, wishlist: false },
  { id: 's12', name: 'Athonian Camoshade', type: PaintType.Shade, hex: '#394619', owned: false, wishlist: false },
  { id: 's13', name: 'Mortarion Grime', type: PaintType.Shade, hex: '#5b582e', owned: false, wishlist: false },
  { id: 's14', name: 'Tyran Blue', type: PaintType.Shade, hex: '#193958', owned: false, wishlist: false },
  { id: 's15', name: 'Berserker Bloodshade', type: PaintType.Shade, hex: '#6d1822', owned: false, wishlist: false },
  { id: 's16', name: 'Soulblight Grey', type: PaintType.Shade, hex: '#707277', owned: false, wishlist: false },
  { id: 's17', name: 'Targor Rageshade', type: PaintType.Shade, hex: '#3d3136', owned: false, wishlist: false },
  { id: 's18', name: 'Poxwalker Shade', type: PaintType.Shade, hex: '#2d3e36', owned: false, wishlist: false },
  { id: 's19', name: 'Kroak Green', type: PaintType.Shade, hex: '#162e1f', owned: false, wishlist: false },
  { id: 's20', name: 'Cryptek Armourshade', type: PaintType.Shade, hex: '#4d2b22', owned: false, wishlist: false }, // Gloss

  // --- CONTRAST ---
  { id: 'c1', name: 'Black Templar', type: PaintType.Contrast, hex: '#2a2a2a', owned: false, wishlist: false },
  { id: 'c2', name: 'Basilicanum Grey', type: PaintType.Contrast, hex: '#5e6164', owned: false, wishlist: false },
  { id: 'c3', name: 'Space Wolves Grey', type: PaintType.Contrast, hex: '#697987', owned: false, wishlist: false },
  { id: 'c4', name: 'Ultramarines Blue', type: PaintType.Contrast, hex: '#283c82', owned: false, wishlist: false },
  { id: 'c5', name: 'Talassar Blue', type: PaintType.Contrast, hex: '#0060a1', owned: false, wishlist: false },
  { id: 'c6', name: 'Leviadon Blue', type: PaintType.Contrast, hex: '#002446', owned: false, wishlist: false },
  { id: 'c7', name: 'Blood Angels Red', type: PaintType.Contrast, hex: '#981b1e', owned: false, wishlist: false },
  { id: 'c8', name: 'Flesh Tearers Red', type: PaintType.Contrast, hex: '#6b1517', owned: false, wishlist: false },
  { id: 'c9', name: 'Baal Red', type: PaintType.Contrast, hex: '#b00e0e', owned: false, wishlist: false },
  { id: 'c10', name: 'Doomfire Magenta', type: PaintType.Contrast, hex: '#9e0f48', owned: false, wishlist: false },
  { id: 'c11', name: 'Magos Purple', type: PaintType.Contrast, hex: '#9c6b94', owned: false, wishlist: false },
  { id: 'c12', name: 'Luxion Purple', type: PaintType.Contrast, hex: '#5a3870', owned: false, wishlist: false },
  { id: 'c13', name: 'Shyish Purple', type: PaintType.Contrast, hex: '#3d1d3f', owned: false, wishlist: false },
  { id: 'c14', name: 'Wyldwood', type: PaintType.Contrast, hex: '#4a3223', owned: false, wishlist: false },
  { id: 'c15', name: 'Cygor Brown', type: PaintType.Contrast, hex: '#3b2621', owned: false, wishlist: false },
  { id: 'c16', name: 'Snakebite Leather', type: PaintType.Contrast, hex: '#6d4625', owned: false, wishlist: false },
  { id: 'c17', name: 'Gore-grunta Fur', type: PaintType.Contrast, hex: '#5c3424', owned: false, wishlist: false },
  { id: 'c18', name: 'Garaghak\'s Sewer', type: PaintType.Contrast, hex: '#4a3627', owned: false, wishlist: false },
  { id: 'c19', name: 'Black Legion', type: PaintType.Contrast, hex: '#1f1f1f', owned: false, wishlist: false },
  { id: 'c20', name: 'Ratling Grime', type: PaintType.Contrast, hex: '#332d29', owned: false, wishlist: false },
  { id: 'c21', name: 'Mantis Warriors Green', type: PaintType.Contrast, hex: '#668229', owned: false, wishlist: false },
  { id: 'c22', name: 'Striking Scorpions Green', type: PaintType.Contrast, hex: '#00853e', owned: false, wishlist: false },
  { id: 'c23', name: 'Ironjawz Yellow', type: PaintType.Contrast, hex: '#d6a419', owned: false, wishlist: false },
  { id: 'c24', name: 'Bad Moon Yellow', type: PaintType.Contrast, hex: '#dedd00', owned: false, wishlist: false },
  { id: 'c25', name: 'Imperial Fist', type: PaintType.Contrast, hex: '#c29d08', owned: false, wishlist: false },
  { id: 'c26', name: 'Aeldari Emerald', type: PaintType.Contrast, hex: '#007a64', owned: false, wishlist: false },
  { id: 'c27', name: 'Terradon Turquoise', type: PaintType.Contrast, hex: '#005f6b', owned: false, wishlist: false },
  { id: 'c28', name: 'Kroxigor Scales', type: PaintType.Contrast, hex: '#007a85', owned: false, wishlist: false },
  { id: 'c29', name: 'Akhelian Green', type: PaintType.Contrast, hex: '#004e61', owned: false, wishlist: false },
  { id: 'c30', name: 'Dark Angels Green', type: PaintType.Contrast, hex: '#002f1e', owned: false, wishlist: false },
  { id: 'c31', name: 'Creed Camo', type: PaintType.Contrast, hex: '#33573c', owned: false, wishlist: false },
  { id: 'c32', name: 'Militarum Green', type: PaintType.Contrast, hex: '#5b643f', owned: false, wishlist: false },
  { id: 'c33', name: 'Aggaros Dunes', type: PaintType.Contrast, hex: '#917b53', owned: false, wishlist: false },
  { id: 'c34', name: 'Skeleton Horde', type: PaintType.Contrast, hex: '#bda981', owned: false, wishlist: false },
  { id: 'c35', name: 'Guilliman Flesh', type: PaintType.Contrast, hex: '#b37b65', owned: false, wishlist: false },
  { id: 'c36', name: 'Fireslayer Flesh', type: PaintType.Contrast, hex: '#a36651', owned: false, wishlist: false },
  { id: 'c37', name: 'Darkoath Flesh', type: PaintType.Contrast, hex: '#8a5847', owned: false, wishlist: false },
  { id: 'c38', name: 'Volupus Pink', type: PaintType.Contrast, hex: '#7e1b4c', owned: false, wishlist: false },
  { id: 'c39', name: 'Sigvald Burgundy', type: PaintType.Contrast, hex: '#541933', owned: false, wishlist: false },
  { id: 'c40', name: 'Aethermatic Blue', type: PaintType.Contrast, hex: '#72b9c8', owned: false, wishlist: false },
  { id: 'c41', name: 'Pylar Glacier', type: PaintType.Contrast, hex: '#a7cdd6', owned: false, wishlist: false },
  { id: 'c42', name: 'Briar Queen Chill', type: PaintType.Contrast, hex: '#b0c3c7', owned: false, wishlist: false },
  { id: 'c43', name: 'Frostheart', type: PaintType.Contrast, hex: '#3e8ba6', owned: false, wishlist: false },
  { id: 'c44', name: 'Celestium Blue', type: PaintType.Contrast, hex: '#1d4175', owned: false, wishlist: false },
  { id: 'c45', name: 'Stormfiend', type: PaintType.Contrast, hex: '#044752', owned: false, wishlist: false },
  { id: 'c46', name: 'Iyanden Yellow', type: PaintType.Contrast, hex: '#ebac25', owned: false, wishlist: false },
  { id: 'c47', name: 'Nazdreg Yellow', type: PaintType.Contrast, hex: '#916e16', owned: false, wishlist: false },
  { id: 'c48', name: 'Gryph-Hound Orange', type: PaintType.Contrast, hex: '#9e4924', owned: false, wishlist: false },
  { id: 'c49', name: 'Ork Flesh', type: PaintType.Contrast, hex: '#005926', owned: false, wishlist: false },
  { id: 'c50', name: 'Karandras Green', type: PaintType.Contrast, hex: '#53872f', owned: false, wishlist: false },
  { id: 'c51', name: 'Gutrippa Flesh', type: PaintType.Contrast, hex: '#6b7d4c', owned: false, wishlist: false },
  { id: 'c52', name: 'Plaguebearer Flesh', type: PaintType.Contrast, hex: '#a5a364', owned: false, wishlist: false },
  { id: 'c53', name: 'Warp Lightning', type: PaintType.Contrast, hex: '#246626', owned: false, wishlist: false },
  { id: 'c54', name: 'Dreadful Visage', type: PaintType.Contrast, hex: '#c4bdce', owned: false, wishlist: false },

  // --- DRY ---
  { id: 'd1', name: 'Praxeti White', type: PaintType.Dry, hex: '#ffffff', owned: false, wishlist: false },
  { id: 'd2', name: 'Etherium Blue', type: PaintType.Dry, hex: '#aecbd8', owned: false, wishlist: false },
  { id: 'd3', name: 'Skink Blue', type: PaintType.Dry, hex: '#529caf', owned: false, wishlist: false },
  { id: 'd4', name: 'Tyrant Skull', type: PaintType.Dry, hex: '#c4bd89', owned: false, wishlist: false },
  { id: 'd5', name: 'Kindleflame', type: PaintType.Dry, hex: '#f49c88', owned: false, wishlist: false },
  { id: 'd6', name: 'Lucius Lilac', type: PaintType.Dry, hex: '#b69bc9', owned: false, wishlist: false },
  { id: 'd7', name: 'Changeling Pink', type: PaintType.Dry, hex: '#e7a6bc', owned: false, wishlist: false },
  { id: 'd8', name: 'Hellion Green', type: PaintType.Dry, hex: '#84c7a9', owned: false, wishlist: false },
  { id: 'd9', name: 'Underhive Ash', type: PaintType.Dry, hex: '#bfb79a', owned: false, wishlist: false },
  { id: 'd10', name: 'Hexos Palesun', type: PaintType.Dry, hex: '#f5e290', owned: false, wishlist: false },
  { id: 'd11', name: 'Eldar Flesh', type: PaintType.Dry, hex: '#e8c088', owned: false, wishlist: false },
  { id: 'd12', name: 'Sylvaneth Bark', type: PaintType.Dry, hex: '#5e5347', owned: false, wishlist: false },
  { id: 'd13', name: 'Terminatus Stone', type: PaintType.Dry, hex: '#c0b096', owned: false, wishlist: false },
  { id: 'd14', name: 'Longbeard Grey', type: PaintType.Dry, hex: '#babebd', owned: false, wishlist: false },
  { id: 'd15', name: 'Necron Compound', type: PaintType.Dry, hex: '#8d9294', owned: false, wishlist: false },
  { id: 'd16', name: 'Golden Griffon', type: PaintType.Dry, hex: '#c49848', owned: false, wishlist: false },
  { id: 'd17', name: 'Sigmarite', type: PaintType.Dry, hex: '#d9b864', owned: false, wishlist: false },
  { id: 'd18', name: 'Stormshield', type: PaintType.Dry, hex: '#bcbbbd', owned: false, wishlist: false },
  { id: 'd19', name: 'Chronus Blue', type: PaintType.Dry, hex: '#4e7fa0', owned: false, wishlist: false },
  { id: 'd20', name: 'Imrik Blue', type: PaintType.Dry, hex: '#1f5982', owned: false, wishlist: false },
  { id: 'd21', name: 'Astorath Red', type: PaintType.Dry, hex: '#c53e3a', owned: false, wishlist: false },
  { id: 'd22', name: 'Ryza Rust', type: PaintType.Dry, hex: '#d66e28', owned: false, wishlist: false },
  { id: 'd23', name: 'Niblet Green', type: PaintType.Dry, hex: '#589344', owned: false, wishlist: false },
  { id: 'd24', name: 'Dawnstone Dry', type: PaintType.Dry, hex: '#6e7578', owned: false, wishlist: false },

  // --- TECHNICAL ---
  { id: 't1', name: 'Blood for the Blood God', type: PaintType.Technical, hex: '#5f0c0e', owned: false, wishlist: false },
  { id: 't2', name: 'Nihilakh Oxide', type: PaintType.Technical, hex: '#6abfbb', owned: false, wishlist: false },
  { id: 't3', name: 'Nurgle\'s Rot', type: PaintType.Technical, hex: '#8a9934', owned: false, wishlist: false },
  { id: 't4', name: 'Typhus Corrosion', type: PaintType.Technical, hex: '#3c362d', owned: false, wishlist: false },
  { id: 't5', name: 'Tesseract Glow', type: PaintType.Technical, hex: '#64b937', owned: false, wishlist: false },
  { id: 't6', name: 'Stirland Mud', type: PaintType.Technical, hex: '#463526', owned: false, wishlist: false },
  { id: 't7', name: 'Stirland Battlemire', type: PaintType.Technical, hex: '#2f2319', owned: false, wishlist: false },
  { id: 't8', name: 'Astrogranite', type: PaintType.Technical, hex: '#6e6e6e', owned: false, wishlist: false },
  { id: 't9', name: 'Astrogranite Debris', type: PaintType.Technical, hex: '#555555', owned: false, wishlist: false },
  { id: 't10', name: 'Armageddon Dust', type: PaintType.Technical, hex: '#bfa965', owned: false, wishlist: false },
  { id: 't11', name: 'Armageddon Dunes', type: PaintType.Technical, hex: '#a89253', owned: false, wishlist: false },
  { id: 't12', name: 'Martian Ironearth', type: PaintType.Technical, hex: '#a85440', owned: false, wishlist: false },
  { id: 't13', name: 'Martian Ironcrust', type: PaintType.Technical, hex: '#8f4635', owned: false, wishlist: false },
  { id: 't14', name: 'Agrellan Earth', type: PaintType.Technical, hex: '#8f7e62', owned: false, wishlist: false },
  { id: 't15', name: 'Agrellan Badland', type: PaintType.Technical, hex: '#756750', owned: false, wishlist: false },
  { id: 't16', name: 'Valhallan Blizzard', type: PaintType.Technical, hex: '#e8e8e8', owned: false, wishlist: false },
  { id: 't17', name: 'Spiritstone Red', type: PaintType.Technical, hex: '#9e1b21', owned: false, wishlist: false },
  { id: 't18', name: 'Soulstone Blue', type: PaintType.Technical, hex: '#004a80', owned: false, wishlist: false },
  { id: 't19', name: 'Waystone Green', type: PaintType.Technical, hex: '#005d36', owned: false, wishlist: false },
  { id: 't20', name: 'Lahmian Medium', type: PaintType.Technical, hex: '#f2f2f2', owned: false, wishlist: false },
  { id: 't21', name: 'Contrast Medium', type: PaintType.Technical, hex: '#f2f2f2', owned: false, wishlist: false },
  { id: 't22', name: 'Ardcoat', type: PaintType.Technical, hex: '#f0f0f0', owned: false, wishlist: false },
  { id: 't23', name: 'Stormshield', type: PaintType.Technical, hex: '#d9d9d9', owned: false, wishlist: false },
  { id: 't24', name: 'Liquid Green Stuff', type: PaintType.Technical, hex: '#4d6e45', owned: false, wishlist: false },

  // --- SPRAY ---
  { id: 'sp1', name: 'Chaos Black Spray', type: PaintType.Spray, hex: '#231f20', owned: false, wishlist: false },
  { id: 'sp2', name: 'Corax White Spray', type: PaintType.Spray, hex: '#ffffff', owned: false, wishlist: false },
  { id: 'sp3', name: 'Grey Seer Spray', type: PaintType.Spray, hex: '#aebec1', owned: false, wishlist: false },
  { id: 'sp4', name: 'Wraithbone Spray', type: PaintType.Spray, hex: '#ded4b6', owned: false, wishlist: false },
  { id: 'sp5', name: 'Macragge Blue Spray', type: PaintType.Spray, hex: '#0d407f', owned: false, wishlist: false },
  { id: 'sp6', name: 'Mephiston Red Spray', type: PaintType.Spray, hex: '#960c12', owned: false, wishlist: false },
  { id: 'sp7', name: 'Zandri Dust Spray', type: PaintType.Spray, hex: '#9e915c', owned: false, wishlist: false },
  { id: 'sp8', name: 'Retributor Armour Spray', type: PaintType.Spray, hex: '#c1974d', owned: false, wishlist: false },
  { id: 'sp9', name: 'Leadbelcher Spray', type: PaintType.Spray, hex: '#888d8f', owned: false, wishlist: false },
  { id: 'sp10', name: 'Mechanicus Standard Grey Spray', type: PaintType.Spray, hex: '#3d4547', owned: false, wishlist: false },
  { id: 'sp11', name: 'Munitorum Varnish', type: PaintType.Spray, hex: '#e5e7eb', owned: false, wishlist: false },
  { id: 'sp12', name: 'White Scar Spray', type: PaintType.Spray, hex: '#ffffff', owned: false, wishlist: false },
];
